// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infra

import (
	"github.com/alert666/alertmanager-agent/base/app"
	"github.com/alert666/alertmanager-agent/base/server"
	"github.com/alert666/alertmanager-agent/pkg/agent"
	"github.com/alert666/alertmanager-agent/pkg/health"
	"github.com/alert666/alertmanager-agent/pkg/kube"
)

// Injectors from wire.go:

// InitApplication wires up the full dependency graph.
func InitApplication() (*app.Application, func(), error) {
	kubeInterface, err := kube.ProvideKubeClient()
	if err != nil {
		return nil, nil, err
	}
	agentAgent, err := agent.NewAgent(kubeInterface)
	if err != nil {
		return nil, nil, err
	}
	server, err := health.ProvideHealthServer(agentAgent)
	if err != nil {
		return nil, nil, err
	}
	v := provideServers(agentAgent, server)
	application := app.NewApplication(v)
	return application, func() {
	}, nil
}

// wire.go:

// provideServers collects all ServerInterface implementations into a slice
// so Application can run them both.
func provideServers(agent2 *agent.Agent, healthSrv *health.Server) []server.ServerInterface {
	return []server.ServerInterface{agent2, healthSrv}
}
