// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infra

import (
	"github.com/alert666/alertmanager-agent/base/app"
	"github.com/alert666/alertmanager-agent/pkg/agent"
	"github.com/alert666/alertmanager-agent/pkg/kube"
)

// Injectors from wire.go:

// InitApplication wires up the full dependency graph.
func InitApplication() (*app.Application, func(), error) {
	kubeInterface, err := kube.ProvideKubeClient()
	if err != nil {
		return nil, nil, err
	}
	agentAgent, err := agent.NewAgent(kubeInterface)
	if err != nil {
		return nil, nil, err
	}
	application := app.NewApplication(agentAgent)
	return application, func() {
	}, nil
}
